### ISSUE TITLE
SJMC plugins incompatible with EssentialsChat

### ISSUE THREAD

**Issue by censink-** [Lebroncraft/public#1]
EssentialsChat fails to display the configured chat format when SJMC plugins are installed, resulting in default `<username> message` format without rank display.

No errors appear on console

Using latest versions (build #9) of Essentials and EssentialsChat
zPermissions appears to be functioning fine as data is successfully imported from database and displayed in `/perm` commands

**Comment by AlastairWilkins** [comment]
Fixed issue #1 causing Essentials Chat to be overridden by SJMC Core's chat feature. Essentials chat is now fully functioning.
