### ISSUE TITLE
HELP PLEASE CrewModPack

### ISSUE THREAD

**Issue by iiLEGACY** [Lebroncraft/public#10]
I already have the new launcher and i did everything it said in the text but when i try to start it it closes.. i dont know what to do now.. 

Pls help me

**Comment by censink-** [comment]
Could you copy the text from the 'Game Output (username)' tab?
Put it on http://pastebin.com please

**Comment by NobodyCraft** [comment]
@censink- http://pastebin.com/mQ21D6r6

**Comment by iiLEGACY** [comment]
@censink- im sorry i reacted so late but yeah i'll do it

**Comment by iiLEGACY** [comment]
@censink- http://pastebin.com/Y8ZfBNYA

**Comment by AlastairWilkins** [comment]
You seem to be missing mods?

**Comment by iiLEGACY** [comment]
O uhm idk 

Verzonden van mijn HTC

----- Reply message -----
Van: "AlastairWilkins" notifications@github.com
Aan: "Lebroncraft/public" public@noreply.github.com
CC: "iiLEGACY" uzmansaebu@hotmail.com
Onderwerp: [public] HELP PLEASE CrewModPack (#10)
Datum: wo, mrt. 18, 2015 12:02

You seem to be missing mods?

&mdash;
