### ISSUE TITLE
CAN'T FIND 'INSTALL CLIENT' WITH THE FORGE INSTALLER

### ISSUE THREAD

**Issue by Kevin102030** [Lebroncraft/public#11]
I clicked into the forge installer there is no install client. (sorry i'm a tech noob :'( don't make fun of me)

**Comment by censink-** [comment]
Could you screenshot it? you can drag the screenshot image into the reply text box. You can also use puush or Gyazo if you have it installed ;)

**Comment by Kevin102030** [comment]
![](http://i.gyazo.com/b13ffd4a530d71235a52c9f26611f59e.png)

![](http://i.gyazo.com/f588c026fce2a5e098e7ec95641c81bb.png)

**Comment by Kevin102030** [comment]
@censink-

**Comment by censink-** [comment]
You need to run the forge-installer.jar, and not extract it

**Comment by Kevin102030** [comment]
@censink- open in winrar?

**Comment by Kevin102030** [comment]
what do you run forge-installer.jar with?

**Comment by Kevin102030** [comment]
@censink-

**Comment by Villisca** [comment]
You run the installer with the Java RE

**Comment by censink-** [comment]
Indeed

**Comment by Villisca** [comment]
You can right-click the program and selet open with, itll give you a list of programs. Select "Java(TM )Platform SE Binary"

**Comment by Villisca** [comment]
Thatll let you run .jar executables.

**Comment by Kevin102030** [comment]
ok thank you

**Comment by Kevin102030** [comment]
@Villisca

**Comment by censink-** [comment]
So you were able to install (and run) the modpack?

**Comment by AlastairWilkins** [comment]
Presuming so.
