### ISSUE TITLE
Crew Modpack Not Working on Macs.

### ISSUE THREAD

**Issue by MercuryKJ** [Lebroncraft/public#112]
My friends and I want to start a private Minecraft server with the Crew Modpack V3 installed. I have installed the modpack on my own computer, and have walked four other people through installing the modpack. I've attempted to walk two of my friends through installing the modpack on their Macs. I do it the exact same way I've done on 5 other PCs, and I've tried on the Macs multiple times. But, on the Macs they will try and start Minecraft and their computer will stay on the Mojang screen. I'm not sure how to fix this, so any help will be appreciated. Also, I am sorry I am not posting this on the crewmod issue tracker, but it does not seem to exist.

**Comment by censink-** [comment]
Some mods are incompatible with OS X, unfortunately.
Use the Mac- and Linux-compatible version (V1).

Sorry for the late reply (and absence of the crewmod repository)
