### ISSUE TITLE
Installer not Running (Crew Mod Pack)

### ISSUE THREAD

**Issue by rmacdizzy** [Lebroncraft/public#12]
When I try to click "Install Client"  I get an error message saying "You need to run the version 1.7.10 manually at least one",  Not sure exactly what I am doing wrong, probably a very simple fix.

**Comment by censink-** [comment]
Try creating a vanilla profile for minecraft 1.7.10, and run it once

**Comment by rmacdizzy** [comment]
That worked! Thank you!
