### ISSUE TITLE
Fatally Missing Blocks and Items {error} (CrewMod Pack)

### ISSUE THREAD

**Issue by Villisca** [Lebroncraft/public#13]
Trying to host a local CrewMod server for myself and my brothers. I have installed the server and client side Forge versions. I have selected the Forge Profile, I even copied all the mods into my local client side(appdata/.minecraft/mods) mod folder. This is the only issue I get when trying to login to the server using IP: localhost.
Edit 1: I forgot to mention that I updated RAM argument to 5gb

**Comment by censink-** [comment]
What is giving you the error, the server or minecraft?

**Comment by Villisca** [comment]
Client-side error. The server runs fine.

**Comment by censink-** [comment]
Can you copy the text in the 'Game Output (username)' tab to http://pastebin.com?

**Comment by Villisca** [comment]
Where's is game output located? In my appdata? Or The server files?

**Comment by censink-** [comment]
In your Minecraft launcher (Be sure to leave the launcher open when launching the game)

**Comment by Villisca** [comment]
The Launcher log then?

**Comment by censink-** [comment]
The tab only appears when the game is running

**Comment by Villisca** [comment]
Alright I see it now, just a moment.

**Comment by Villisca** [comment]
http://pastebin.com/V3vXBHvA

**Comment by censink-** [comment]
Thanks.
As you can see, 0 mods are missing. However, the Flan content packs are missing..

You must've forgotten to copy the Flan folder over to your server or client directory

**Comment by Villisca** [comment]
Yep that was it. Thank you!

**Comment by censink-** [comment]
No problem, enjoy the pack :)
