### ISSUE TITLE
Crashing!!!

### ISSUE THREAD

**Issue by amandayuo123** [Lebroncraft/public#14]
Everything worked up until I pressed the play button. My game crashes on the installing screen. I updated my Java and i don't know how to get more WAMs. I need help fixing this.

**Comment by censink-** [comment]
Can you copy the text in the 'Game Output (username)' tab to http://pastebin.com?

**Comment by amandayuo123** [comment]
where is the game output located?

**Comment by censink-** [comment]
In the minecraft launcher, it only appears after you click the Play button

**Comment by amandayuo123** [comment]
I copied the game input and sent it

**Comment by amandayuo123** [comment]
Hold on

**Comment by amandayuo123** [comment]
http://pastebin.com/TdNSHiTn

**Comment by amandayuo123** [comment]
http://pastebin.com/QcY4PJ6c

**Comment by censink-** [comment]
Either Forge wasn't fully installed or it runs out of RAM very quickly. Try reinstalling Forge and upping the RAM (there are guides on the internet)
