### ISSUE TITLE
Game crash - brewingapi

### ISSUE THREAD

**Issue by Janibagian** [Lebroncraft/public#15]
I load the game and it crashes and says brewingapi:any and so i tried and manually downlaoding the mod and putting it with the other mods and it still doesn't recognize it if you have any ideas could you please tell me?
thanks you

**Comment by censink-** [comment]
When does it crash, right after starting?

**Comment by Janibagian** [comment]
it brings up the first mojang screen and then goes black for a second and gives me that message

**Comment by censink-** [comment]
Could you copy the text from the 'Game Output (username)' tab in your minecraft launcher on to http://pastebin.com?

**Comment by Janibagian** [comment]
yeah on sec

**Comment by Janibagian** [comment]
*one

**Comment by Janibagian** [comment]
im sorry i really dont understand what the game output is will you tell me what it is and where I can find it?

**Comment by censink-** [comment]
It's a tab in the minecraft launcher, it appears after you click the Play button
![](http://i.gyazo.com/646d8c82b2220f3c5fac58ff1cdffb36.png)

**Comment by Janibagian** [comment]
mine doesn't appear it just has the screen where it says brewing api:any cant be found

**Comment by Janibagian** [comment]
would it help if i screencaptured it and sent you the picture of the screen?

**Comment by Janibagian** [comment]
![forge pic](https://cloud.githubusercontent.com/assets/11480027/6653960/2489003a-ca6c-11e4-9ee0-833c7199024b.png)

**Comment by censink-** [comment]
Could you put the content of ForgeModLoader-client-0.log on pastebin? This error isn't telling much :/
