### ISSUE TITLE
Mods Wont Work?

### ISSUE THREAD

**Issue by StanleyJoness** [Lebroncraft/public#16]
I am trying to play the mods on single player. I have done the forge installer and moved both the "mod" and "flan" folders into my minecraft folder. However when I run minecraft it says 3 mods are on. I've tried singleplayer and it says "TEST TEST 2 DISABLED". I'm using a mac and I'm brand new to mods, any help would be appreciated thanks.

**Comment by censink-** [comment]
Does it give you any errors in the 'Game Output (username)' tab from your minecraft launcher, when you click Play?

**Comment by StanleyJoness** [comment]
Nope, says downloading a few things which is pretty much instant than closes as it opens up the game. I added a few pics if they help.
![screen shot 2015-03-14 at 7 47 37 pm](https://cloud.githubusercontent.com/assets/11481362/6654454/2229b188-ca83-11e4-89db-994825f589f5.png)
![screen shot 2015-03-14 at 7 47 56 pm](https://cloud.githubusercontent.com/assets/11481362/6654455/236f6a06-ca83-11e4-8d7c-ffddd9588563.png)
![screen shot 2015-03-14 at 7 48 29 pm](https://cloud.githubusercontent.com/assets/11481362/6654456/2632b072-ca83-11e4-86c5-ba3b6eef4b95.png)

**Comment by censink-** [comment]
There's an option in the profile editor to leave it (the launcher) opened when the game is running, it's called Launcher Visibility

**Comment by StanleyJoness** [comment]
Heres the Output
![screen shot 2015-03-15 at 8 56 36 am](https://cloud.githubusercontent.com/assets/11481362/6656751/593e389c-caf1-11e4-9d49-a8e175d48b3c.png)
![screen shot 2015-03-15 at 8 56 48 am](https://cloud.githubusercontent.com/assets/11481362/6656752/5aa8e556-caf1-11e4-950b-711e7e48155a.png)

**Comment by censink-** [comment]
There are no errors when it is searching through the 'mods' folder, please make sure you copied it to the right place (and has the correct name)

**Comment by StanleyJoness** [comment]
I did put them in the minecraft folder which is where the instructions say to. Correct name?

**Comment by StanleyJoness** [comment]
I believe this is something that could be causing it?
![screen shot 2015-03-15 at 7 14 28 pm](https://cloud.githubusercontent.com/assets/11481362/6659654/93dc6e64-cb47-11e4-8403-05ce083df5f8.png)

**Comment by censink-** [comment]
That is a dummy mods list as far as i'm aware. And if it's not, it indicated there are only 3 mods (the ones included with Forge).
The mods folder is called 'mods' (no capital M) and in your case should be located in
/Users/Cal/Library/Application Support/minecraft/
