### ISSUE TITLE
when i launch up a world it crashes PLEASE HELP

### ISSUE THREAD

**Issue by Pony-Destroyer** [Lebroncraft/public#20]
http://pastebin.com/z1aZ7BZN

**Comment by censink-** [comment]
[00:02:07] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load

Did you copy both the 'mods' and 'Flan' folders to your minecraft folder?

**Comment by Pony-Destroyer** [comment]
Yea 
Still wont let the world load

**Comment by censink-** [comment]
When you click the Mods button in Minecraft's main menu, how many mods do you see?

**Comment by Pony-Destroyer** [comment]
3
Minecraft Coder pack 
Forge mod Loader 
Minecraft forge

**Comment by censink-** [comment]
Then it was unable to read all mods in the mods folder, those 3 are the default ones, listed with Forge on default.
Please ensure you copied the folder into the right directory :/
