### ISSUE TITLE
The seed wont for me, can you help ?

### ISSUE THREAD

**Issue by mexicanIduck** [Lebroncraft/public#25]
can anyone take a pic of the seed on how they put it in and put it on the comments

**Comment by mexicanIduck** [comment]
help ?

**Comment by mexicanIduck** [comment]
can anyone take a pic of the seed on how they put it in and put it on the comments

**Comment by censink-** [comment]
The crew uses the seed 'Lebron', without quotes obviously ;)
If that seed doesn't work, we'll look into it.
Please note you do not spawn where Speedy started his series, that's a couple hundred blocks away.

**Comment by BlueBeatz** [comment]
the seed doesnt work still i end up in a type of swamp that appears only in the biomes o plenty mod
 plz help!

**Comment by censink-** [comment]
Thanks for reporting, it's being looked into and we'll keep you updated through https://github.com/Lebroncraft/public/issues/38 as it contains some more details
