### ISSUE TITLE
The mods aren't there

### ISSUE THREAD

**Issue by Elduroto** [Lebroncraft/public#26]
I apologize if there is some obvious way to do this but I am a guy on the internet who instead of dealing with this myself I will wait for someone else to do this for me: I have the forge installed correctly but the crew modpack is not installed on it already and it is not listed how to install that and I have no idea how to install it and when I try the Youtube tutorials they do not help me whatsoever. So if anyone installed it successfully please message me on skype: Elduroto and make sure that the first thing you type to me is you know how to install the mods

**Comment by mrmango03** [comment]
same for me! idk what to do and its very frustrating

**Comment by mrmango03** [comment]
it says:test one
           test two
           disabled 
in red letters and it wont work

**Comment by AlastairWilkins** [comment]
Please view the '**How to install?**' section of [this website](http://lebroncraft.com/crewmod/)
