### ISSUE TITLE
fatally missing blocks and items connection issue

### ISSUE THREAD

**Issue by Scubadivingmonk** [Lebroncraft/public#27]
I started up a server but when I try to connect the connection is lost with the message fatally missing blocks and items. My friend has connected fine to the server but I still can't, need help!

**Comment by mrmango03** [comment]
do you need to make a server?

**Comment by Scubadivingmonk** [comment]
no I already made it and my friend is able to connect to it and everything

**Comment by mrmango03** [comment]
If I go into mod options it says test 1
Test 2
Disabled

Can you help me with that?

**Comment by Scubadivingmonk** [comment]
bro i'm the one with the problem here

**Comment by AlastairWilkins** [comment]
Have you on your client installed **all** the correct mods? "Fatally msising blocks and items" says to me you're missing a mod that is pretty essential in order to play?

**Comment by AlastairWilkins** [comment]
Most likely duplicate of issue #13

**Comment by AlastairWilkins** [comment]
Most likely a duplicate of #13

**Comment by AlastairWilkins** [comment]
Re-closing as it didn't seem to close before
