### ISSUE TITLE
Shutting down Internal server

### ISSUE THREAD

**Issue by ChicoX10** [Lebroncraft/public#28]
Hi! So I've installed the Client folder and I did all I was suposed to do. I have 6G of Wams allocated so its sould not be the problem, but when I try to start a solo game, it crash. Just after the ''Generating terrain'' appear, the ''Shutting Down Internal Server'' pop up. 

I can see all the 28 mods active, but I just can't play. I never had problem with minecraft before, that would be super cool if someone know where is the problem. Here's what the report file say: 

http://pastebin.com/AajUzNWk 

Sorry for any mistakes, english is not my first language

**Comment by AlastairWilkins** [comment]
Are you able to load worlds without any mods installed?

**Comment by ChicoX10** [comment]
Yes, the world load when I choose the latest version (instead of 1.7.10 Forge)

**Comment by iAmTijl** [comment]
https://github.com/Lebroncraft/public/issues/22
I could fix it by removing the .minecraft folder
copy your saves to you desktop temporarily

**Comment by StrikingGerbil** [comment]
I'm getting this problem too, and I don't know what to do. this is what i put into the JVM arguments box:   -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn3G. Should i change it in some way?

**Comment by censink-** [comment]
-Xmx4G
is enough (and does the same), if changing that doesn't fix it, read the issue @iAmTijl mentioned

**Comment by ChicoX10** [comment]
I don't understand how changing the location of my .minecraft folder will change something, but I'll try it right meow

**Comment by AlastairWilkins** [comment]
Did this help your issue?

**Comment by ChicoX10** [comment]
No, it didn't work :( I even tried to reinstall minecraft, use Java 7 instead of Java 8...   After the "shutting down internal server" message, the JAVA SE environment is crashing, whenever I use the 1.7.10 version (even without Mods)! So I really think the Mods are working and the problem might be my Java. Any Idea?

**Comment by ChicoX10** [comment]
Sorry Alastair, I wasnt able to load my world ON 1.7.10 without mods, but it's fine on the lattest version :)

**Comment by AlastairWilkins** [comment]
Have you tried making generating a new world (whilst mods are installed)?
Also, could you send me a copy of your log on startup of minecraft when it loads the mods (upload to [pastebin](pastebin.com))

**Comment by ChicoX10** [comment]
Yes, the world will genrerate with the mods on, but it will crash right after. But, if I go back on 1.8.3, I can access this Modded world (with weird biome), but the mods won't be there because I can't play it on the 1.7.10 Forge (where the mods are playable)

Here's everything in the Launcher Log, from the moment I start the game, until it crash

http://pastebin.com/frT5ULyq

**Comment by AlastairWilkins** [comment]
How strange. 

The only thing I can see going wrong with your client is a load of IOExceptions (errors thrown when the game can't do something related to files), stream closed could possible indicate something to do with attempting to write data. 

Try move your .minecraft folder to the desktop and let me know what happens. 

If not, @censink may be able to assist you further

**Comment by censink-** [comment]
8800 identical errors, all within 1 second. I'm pretty sure that is the cause of your crash :p

As it happens when it is cleaning up files from the version, my only guess would be to delete the entire version folder, and installing Forge again.

**Comment by ChicoX10** [comment]
I've already tried bot of these options, but I'm gonna try it again... Is there

 a way to move my .minecraft folder on my desktop without losing all of my profile in minecraft? because this happen last time I moved the folder

**Comment by StrikingGerbil** [comment]
i just re-downloaded everything and it worked

**Comment by Rafa25** [comment]
@ChicoX10 I had the same problem...Through a little research on minecraft forums I tried a suggestion and it worked for me.  It was suggested that I increase the PermSize of Java.  Add to your JVM Arguments '-XX:MaxPermSize=128'...I know it sounds random but I had the same exact issue and it worked for me.

**Comment by ChicoX10** [comment]
It's not working, everytime my Java SE 8 Crash, all the mods seems to load in the log session...

If JAVA was a person, I will shot it -_-

**Comment by lb548883** [comment]
Hi

I am also having this problem. The crash report is below.

http://pastebin.com/mJ0gSE0G

If anyone is able to help it would be appreciated. I have tried everything previously mentioned but none of them worked.

Thank you

**Comment by censink-** [comment]
@ChicoX10 There have been 15 patches to Java 1.8 since you installed your version, consider updating java (and be sure to check if minecraft will run the newly installed version)

**Comment by MrSkate714** [comment]
I am also having the same problem. I am able to start a new singleplayer world and spawn in. Moments later I start to get lag and then it says Shutting Down Internal Server. Can anyone please help with this Issue?

**Comment by rainiedragon** [comment]
I had the same problem. So what I did was go research it on youtube and what i found is that you have to delete the options document located in the .minecraft folder. How you get to that folder is Click Start → Run. If you don't see "Run" try holding down your "Windows" key and press the R key.
Type %appdata% (case doesn't matter but be sure to include the % markers) and click OK.
Then open the .minecraft folder. you will see a document that is titled options.then you click that document then hit the delete button on your computer keyboard.

**Comment by MrSkate714** [comment]
Does that fix anything? Are you able to play the Modpack without problems now?

**Comment by MrSkate714** [comment]
I am still having problems here is the Crash Report
http://pastebin.com/sQfzcX0e
