### ISSUE TITLE
Crew Modpack sever please help asap

### ISSUE THREAD

**Issue by harvey12345** [Lebroncraft/public#29]
I'm making a private server for me and my mates and i'm using on mcprohosting to host the server and I've selected standard mine craft and chosen all the maps and stuff like that and I don't know how to put the crew mod pack on it. I've ask Beeesly and Bz, they tried to help me with it, but I still couldn't put the modpack on

**Comment by AlastairWilkins** [comment]
One for @censink

**Comment by censink-** [comment]
Upload all files (except install.txt) to the server directory, and tell the panel to use the forge jar (forge-1.7.10-10.13.2.1230-universal.jar)

**Comment by harvey12345** [comment]
tahsnk :)
