### ISSUE TITLE
Mod not installing these things

### ISSUE THREAD

**Issue by Kentyy** [Lebroncraft/public#30]
"These libraries failed to download. Try again.

.comtypesafe.akka:akka-actor_2.11:2.3.3, org.scala-lang:scala-reflect:2.11.1"

Help please! :D :kiss:

**Comment by AlastairWilkins** [comment]
This doesn't really look like an issue we have control over.
All I can suggest is to completely reset your Minecraft mods and folders and then install everything fresh, let me know how you get on after that whether it works or doesn't.
Is there anything more to that error log also?

**Comment by Kentyy** [comment]
Ah ok, I'm a noob :stuck_out_tongue_closed_eyes: 

No there isn't anything else to that log.

Also i'm using cracked minecraft if that's a problem? I'm too lazy to buy premium

**Comment by AlastairWilkins** [comment]
I'm not sure whether cracked minecraft would affect this, maybe @censink- can clear this up

**Comment by censink-** [comment]
While i do recommend buying the game (so you can easily play on servers for example), I do not think it stops you from downloading certain libraries.

Like @AlastairWilkins suggested, remove the 'mods' folder, and copy it back in (while the game is closed)
