### ISSUE TITLE
Help mod errors

### ISSUE THREAD

**Issue by vampireboy1461** [Lebroncraft/public#33]
First it says mod error when the service starts running then when you try enjoying it it says my rejected and list a lot of the Forge mods I have checked all of them and they all match between both and they're all there

**Comment by vampireboy1461** [comment]
![image](https://cloud.githubusercontent.com/assets/11507864/6673212/ca7e84c0-cbe7-11e4-81b1-bb04aaa3ae31.jpg)
![image](https://cloud.githubusercontent.com/assets/11507864/6673213/ca94df72-cbe7-11e4-9931-9a5515c2ae82.jpg)

**Comment by censink-** [comment]
Your client loaded all mods, but your server did not (assuming you tried joining a server?)

**Comment by vampireboy1461** [comment]
I was running it on one pc and joining on another

**Comment by vampireboy1461** [comment]
How should I fix the server

**Comment by vampireboy1461** [comment]
Oh and thank you carry much for replying I know a lot of people are having issues

**Comment by AlastairWilkins** [comment]
Install the server pack on the server.

**Comment by vampireboy1461** [comment]
I'm not the brightest but what do you mean

**Comment by AlastairWilkins** [comment]
Go to http://lebroncraft.com/crewmod and read the server install instructions.
