### ISSUE TITLE
Hat mod not working 

### ISSUE THREAD

**Issue by JackT01** [Lebroncraft/public#34]
The hat mod is not working and when I have a look if the binding letter (H) is being taken I can't even see the hat mod in my controls to fix it please help.

**Comment by censink-** [comment]
Is the mod in your mods list? The one you see when you click 'Mods' in minecraft's main menu

**Comment by DamnP** [comment]
I had to go into the control and change the key from h to something else, it was apparently conflicting, when doing so, it worked flawlessly.
