### ISSUE TITLE
Tconstruct breaks tools 

### ISSUE THREAD

**Issue by Ndriqim-H** [Lebroncraft/public#35]
First I downloaded the mods, put it all together and finally after some time they worked, but it wasn't over. I realized after I built a sword and started fighting a goblin, my sword broke immediately after 2 hits (srsl not making it big here) I was confused first but soon realized after I made a pickaxe and started breaking some blocks but then after the 1st hit I saw it's health to 1%. I found out that it was the Tconstruct's fault. PLS help!!!

**Comment by censink-** [comment]
Try reinstalling TConstruct, or the entire 'mods' folder

**Comment by Ndriqim-H** [comment]
Tried that but still not working. Also tried to get the newest Tconstruct even with that it doesn't work.

**Comment by AlastairWilkins** [comment]
Tested with TConstruct, can't see this bug happening so it must be conflicting with other mods you've got installed, but with just the modpack installed it works fine, (tested on multiple computers / accounts).
