### ISSUE TITLE
CrewMod not working

### ISSUE THREAD

**Issue by BeastMode0840** [Lebroncraft/public#36]
I downloaded the mod, followed the instructions, and when I opened minecraft and loaded a world and clicked mod options it says "test 1 TEST 2 DISABLED". How can I fix this?

**Comment by censink-** [comment]
Mod Options doesn't list the mods you have installed, 'Mods' does, and you can find it in the main menu

**Comment by BeastMode0840** [comment]
How do I activate it so it works in one of the worlds?

**Comment by censink-** [comment]
Create a new world to enable all features/mods

**Comment by BeastMode0840** [comment]
When I create a new world it doesn't work.

**Comment by AlastairWilkins** [comment]
Then you have not installed the mods correctly
