### ISSUE TITLE
different biomes...

### ISSUE THREAD

**Issue by DamnP** [Lebroncraft/public#38]
So,I set up  using the biome o plenty... however when i go to the exact coords as seen in Sp33dy's first video, the biome is different.... what gives? I have  redone the installation from scratch multiple times, all the mods work etc...

Sp33dys screenshot on left,  mine on right... http://i.imgur.com/9MGLbi7.png

**Comment by AlastairWilkins** [comment]
As @censink said:

> The crew uses the seed 'Lebron', without quotes obviously ;)
> If that seed doesn't work, we'll look into it.
> Please note you do not spawn where Speedy started his series, that's a couple hundred blocks away.

**Comment by DamnP** [comment]
Yes, I have deleted everything multiple times and  reinstalled  it again, using the seed name and traveled to the coordinates... the lucky block is there at that location, but the biome is different, some of the neighboring biomes are similar to what was seen in the videos, all the hayman with spawner underneath etc, however the "home" base biome is different as seen in the screenshot provided.

**Comment by AlastairWilkins** [comment]
I see, sorry to hear this is happening. It sounds like you're losding all the settings correctly with the world generation so I assume it's an error you're not causing yourself.

However, I just develop plugins and help out here from time to time, so @censink would be the guy to talk to if you need this resolved

**Comment by censink-** [comment]
Thanks for reporting, we'll look into it

**Comment by BlueBeatz** [comment]
When u get on the world with the seed Lebron, could u just do /seed and give us the seed in number form from the crew?

**Comment by DamnP** [comment]
http://i.imgur.com/bL5Bq5T.png

seed # -2022843576

again with a screenshot including the location of the first pic.... showing different biome type.... yes laptop sucks, but its temporary whilst in hospital... thanks for any and all help.

**Comment by DamnP** [comment]
also, it  is weird as the two slime islands in the sky ARE in my world too, just as seen in the crews vids... but biome on ground is different.... hopefully I am not overlooking  something and am just dumb.... I am new to minecraft on the pc, so.....

**Comment by BlueBeatz** [comment]
i have the same thing happening to me thats exactly what i see

**Comment by DamnP** [comment]
hey BlueBeatz, and your /seed shows the same as mine, also used  Lebron?


if so, glad it isn't just me, wonder what the issue is.....

**Comment by BlueBeatz** [comment]
Yep, exact same seed and the terrain is the same, ive tweeted censink_ and he said he will tweet when they have fixed it

**Comment by BlueBeatz** [comment]
anything new with the seed? The anticipation of playing on their world is killing me XD

**Comment by DamnP** [comment]
me too, patiently waiting, lol.

**Comment by DamnP** [comment]
is it possible for YOU (censink_) to upload a .minecraft folder with it all pre-loaded for us to get it right? I'm not sure if that is possible, or the specific folder inside the .minecraft folder that would adjust the proper biomes... just an idea....

**Comment by BlueBeatz** [comment]
its funny cause i dont want to even play the pack unless i play on their world, that way i can explore it so much more and use their videos as tutorials

**Comment by DamnP** [comment]
EXACTLY, i am in the hospital, just refreshing and refreshing hoping for a solution to waste time better... lol.   totally new to pc minecraft let alone mods, but effing thrilled to learn and wishing i could get started, lol. the anticipation is killing me.

**Comment by DamnP** [comment]
on a side note, when the crew looks at the moon and the sun it is rounded?  but not on my world... nor was it any of the times that I loaded and reinstalled the world.

**Comment by BlueBeatz** [comment]
hmmmmm.....

**Comment by BlueBeatz** [comment]
still confused on y it is so hard just to find a seed

**Comment by BlueBeatz** [comment]
and the moon and sun might be that way because they might have a shaders pack or texture pack on, but idk exactly

**Comment by AlastairWilkins** [comment]
We understand your patience and are doing our best to look into this issue.
Sorry for the inconvenience

**Comment by BlueBeatz** [comment]
Yep, it fine though, im pretty sure i can find something else to do in the mean time ;)

**Comment by BlueBeatz** [comment]
Could it be from not downloading all the mods? my pc doesnt handle to flan mods very well so i downloaded the pack and then deleted the few i didnt want, could that effect the seed though? but still, both of us see the same things in the same places

**Comment by DamnP** [comment]
i used all mods, my guess is  no...

**Comment by BlueBeatz** [comment]
hmmmmmm, i really dont know then, ive tried messaging the crew multiple times on twitter if they could give us the seed, but nobody every replys :(

**Comment by DamnP** [comment]
we have it right, Lebron, but there is clearly an error with how it is loading for us...

**Comment by BlueBeatz** [comment]
yah, it really sucks, lol, i wake up every morning turn on the pc and look here right away hoping for an answer or solution, its gonna be time to give up soon tho, but what can u do? :/

**Comment by BlueBeatz** [comment]
Hey, btw my skype name is blue_beatz, so if u would ever like to play some minecraft sometime, just let me know! :)

**Comment by DamnP** [comment]
how old are you?

**Comment by BlueBeatz** [comment]
15

**Comment by DamnP** [comment]
okay, censink_, I spent all day again, deleting and re-installing everything, I even tried doing the requested update of forge,  for the minecraft 1.7.10

I even screenshotted the  first time it loaded up, the last ti e I tried as it said some invtweeks things, doubtful that is the source of our problems, but just in  case.... I didn't  update the buildcraft though.....  

http://i.imgur.com/NnTsDW2.png

Any other idea on what I can attempt? pretty much at a loss here...

**Comment by BlueBeatz** [comment]
Probably doesn't help whatsoever but that's where I spawned everytime too, lol, I've given up pretty much :/

**Comment by AlastairWilkins** [comment]
@BlueBeatz commented 16 hours ago

> Hey, btw my skype name is blue_beatz, so if u would ever like to play some minecraft sometime, just let me know! :)

@DamnP commented 15 hours ago

> how old are you?

@BlueBeatz commented 14 hours ago

> 15

Can I just remind you this isn't a place for personal conversations, but more-so for the use of tracking and resolving issues, please refrain from having personal chats within these comments as it only makes it a pain to scroll through and work out what's going on.
Thank you.

Going to lock this issue until we can provide you with some feedback / a fix.

Thanks
