### ISSUE TITLE
Crashing Problems

### ISSUE THREAD

**Issue by CameronCen** [Lebroncraft/public#39]
I load the game up and I see that all the mods are working fine, but when log into single player My game drops to 0 fps and the game freezes and eventually crashed. Please help!

**Comment by AlastairWilkins** [comment]
Please provide us with the log for when you crash from your client output, upload it to [pastebin](pastebin.com)

**Comment by CameronCen** [comment]
@AlastairWilkins sorry the game docent crash, but it freezes at 0 fps and eventually goes to a white screen or a screen that says "shutting down internal servers". I don't know if i need more ram or not, but maybe its just simple.

**Comment by AlastairWilkins** [comment]
Try allocating more RAM if possible, and regardless of a crash it would be helpful to see the log of your client during this. 

Let me know how you get on with more RAM and if it happens again, please show me the log

**Comment by CameronCen** [comment]
@AlastairWilkins I tried to find the place to allocate more ram in "edit profile" such as the website said, but i can't seem to find it.

**Comment by AlastairWilkins** [comment]
[This](https://m.youtube.com/watch?v=BiX6yRzW16w) should help

**Comment by CameronCen** [comment]
-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M (This is in my JVM arguments under java settings advanced in edit profile), I saw this video before to try to fix it myself, but this person is using windows i am currently on mac and the code is different, when i run the game with the code he suggested I cannot run the game at all! :(

**Comment by CameronCen** [comment]
@AlastairWilkins Sorry forgot to tag you look up

**Comment by CameronCen** [comment]
@AlastairWilkins  I think i fixed it Thankyou for all the help if i have anymore questions ill ask thank you again

**Comment by censink-** [comment]
You can leave out all arguments except the '-Xmx' one ;) but glad to hear you fixed it already, comment or reopen if you run into similar issues again
