### ISSUE TITLE
Can't get past ForgeInstaller

### ISSUE THREAD

**Issue by bmsanford33** [Lebroncraft/public#40]
I try to run ForgeInstaller, but it says "you have to run 1.7.10 at least once" what do I do?

**Comment by AlastairWilkins** [comment]
Run a clean version of 1.7.10 first, pretty self explanatory

**Comment by bmsanford33** [comment]
Still not working!!

**Comment by Castiels-Vessel** [comment]
if you go into the profile in launcher and edit you can set it to load the game in 1.7.10 that is what you need to do.
