### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by ghost** [Lebroncraft/public#42]
_EDIT: 18/03/15 @AlastairWilkins: Cleaned up due to log being posted, please use [pastebin](http://pastebin.com) in future!!_

I am a complete noob I will admit this but I am extremely confused. I thought I did what the instructions told me to do but when I load a new world nothing happens. No mods are there. I have forge installed and the main menu says mods. I went back to the files and even clicked on the mods, thinking that's what I do to install them, but it just says error and that it was corrupt. I then deleted those files and re downloaded all of that and now it doesn't do anything and game output comes up with this:

http://pastebin.com/PaVYb8wT

**Comment by AlastairWilkins** [comment]
@censink

**Comment by ghost** [comment]
I'm sorry I will do that next time. Any idea on how to fix this? I redownloaded it again but It still doesn't work.
