### ISSUE TITLE
NEI (Not Enough Items) Mod

### ISSUE THREAD

**Issue by HypertonicWake** [Lebroncraft/public#43]
The Not Enough Items Mod is not showing up in game when I hit "E" to go to my inventory. It is listed in the mods that are installed but its still not showing up though. Please Help.

**Comment by AlastairWilkins** [comment]
@HypertonicWake 
From the official guide for Not Enough Items:

> Turn On/Off: Press the “o” key while in the inventory screen. You can change this key by editing the configuration file. 

Have you tried this?

**Comment by HypertonicWake** [comment]
No but I will try it. I will let your guys know otherwise.

Parker's IPhone
