### ISSUE TITLE
Forge Installer: Attempting to run version 1.7.10 for first time fails

### ISSUE THREAD

**Issue by TheNamesIsHolden** [Lebroncraft/public#46]
Shortly after clicking "ok" on the Forge Installer I get a message reading: "You need to run the version 1.7.10 manually at least once." I then went to the Minecraft launcher to see if I could make a new profile that could run this version. I soon found out that the closest version that it will run is: 1.7.2. Please Help.

**Comment by FinalHazard** [comment]
I have the same problem and dont know how to solve it.

**Comment by FinalHazard** [comment]
i also tried forge 1.8 but it didnt work either

**Comment by FinalHazard** [comment]
I FIGURED IT OUT!!!
open minecraft launcher
edit profile. 
go to "use Version" then select 1.7.10
launch minecraft. 
then close it out and try forge again. 
it should work
