### ISSUE TITLE
Creative server ranks able to copy other players plots with W.E 

### ISSUE THREAD

**Issue by BzUrQ** [Lebroncraft/public#49]
Using //pos1 //pos2 players can copy other players plots. Need to remove worldedit.selection.pos node

**Comment by censink-** [comment]
And can they paste?

**Comment by BzUrQ** [comment]
Yeh can paste on their own plots

**Comment by censink-** [comment]
Okay, will remove pos nodes.
Won't they be able to select a plot using the wand?

**Comment by AlastairWilkins** [comment]
Tested with Speedivity, he isn't able to select with the wand in others' plots, but can with //pos1 and //pos2

**Comment by censink-** [comment]
Removed pos and hpos nodes
