### ISSUE TITLE
Members are able to /setspawn in mglobby

### ISSUE THREAD

**Issue by BzUrQ** [Lebroncraft/public#52]

**Comment by censink-** [comment]
Need to remove setspawn node from global perms, and add it to survival & creative's server-permissions

**Comment by censink-** [comment]
Uh oh, i never even added it, thanks john.

```
permissions:
  sjmclobby.setspawn:
    default: op
```

**Comment by censink-** [comment]
Fix permission on `sjmclobby` and add list all available nodes (including trail-specific ones) in plugin.yml please. Players are unable to open the trail/wardrobe interfaces, so we need to know those nodes asap (through skype)

**Comment by AlastairWilkins** [comment]
Provided permissions list of trails and wardrobe via skype.

**Comment by AlastairWilkins** [comment]
**Reopen:** /spawn set is handled by another plugin, not SJMC Lobby.

**Comment by censink-** [comment]
LobbyLib missed permission nodes, trev is fixing it and will deploy
