### ISSUE TITLE
CrewMod Server: When I join my server the tick rate jumps way up. Help?

### ISSUE THREAD

**Issue by Pooted** [Lebroncraft/public#53]

**Comment by censink-** [comment]
Somewhat normal for a server this heavy, the tick rate should revert to a normal amount a little while after joining. It might also occur (higher rate) when you put a heavy load on the server, like spawning a lot of mobs or loading a lot of (new) land

**Comment by Pooted** [comment]
I sat in there for an hour and it still is 400-450 ms
