### ISSUE TITLE
Crewmod pack causing crash

### ISSUE THREAD

**Issue by Will0wHaven** [Lebroncraft/public#55]
I've tried installing this, following the 'read me' instructions and i go to launch the mods, and it keep crashing.The only error message in the crash report is.. "ERROR]: java.io.IOException: Stream closed"
(I can send you the whole crash report it needed).
How do i fix this??

Thanks!

**Comment by AlastairWilkins** [comment]
Try re-locating your .minecraft folder to a different place (e.g. your desktop) and see if this works.
Make sure you close all instances of Minecraft before moving this over.

**Comment by Will0wHaven** [comment]
that fixed it. thank you!!!
