### ISSUE TITLE
Waila messing up NEI

### ISSUE THREAD

**Issue by Rafa25** [Lebroncraft/public#56]
Whenever I add the Waila mod my NEI disappears and I can't search anything.  I would really like to run both mods since most of the crew uses it but I don't understand why it is affecting the NEI.  Thanks in advance.

**Comment by AlastairWilkins** [comment]
When you load the game and click the 'mods' button in the menu, is NEI present?
If it isn't, please provide me with a log of your game output on startup (upload to [pastebin](http://pastebin.com) please)

**Comment by censink-** [comment]
NEI has it's own Waila functionality, you just have to enable it ;) Waila just does it a little bit better.
But it caused lag and messes with NEI, so we chose not to include it in the pack
