### ISSUE TITLE
Setting up a Crew-modded server

### ISSUE THREAD

**Issue by kdanielhaas** [Lebroncraft/public#58]
I currently manage a minecraft server that is run through a third party, as in not hosted on one of the users computers. I have been playing with the crew modpack, and would like to put it on our server. How can I go about doing that? I have been attempting to do so, but with little success. All help is appreciated.

**Comment by AlastairWilkins** [comment]
Please follow the steps [here](http://lebroncraft.com/crewmod/) regarding server installation. 
Make sure you read the 'install.txt' fully.

**Comment by kdanielhaas** [comment]
I have read those instructions, and they seem geared towards setting up a server from your own computer, not how to place them on an already existing 3rd party server. We rent out memory on a server from a website, and manage it through the website.

**Comment by AlastairWilkins** [comment]
We aren't exactly here to teach you how to run a server, only how to use the mod pack. 
Is there some sort of FTP access on your website panel you have to manage the plugins for the server?

If not you'll need to talk to the hosting company about installing your own stuff as this is out of our control.

**Comment by kdanielhaas** [comment]
I'm not asking you to teach me how to run a server, thank you. I have the mods uploaded and they are in the FTP access, but don't seem to function correctly. I wasn't sure if there was a different process for applying them to a 3rd party service instead of hosting your own. 

Thanks for your time,
-K
