### ISSUE TITLE
Popper needs to go Asap from sjmc inv

### ISSUE THREAD

**Issue by BzUrQ** [Lebroncraft/public#59]

**Comment by AlastairWilkins** [comment]
FAO @censink:

**Comment by censink-** [comment]
SJMC won't let me modify the config, plugin needs to be modified >.<

**Comment by AlastairWilkins** [comment]
Modified plugin, removed class that handles the popper gadget and edited the default configuration to now give the pet selector in replacement of the popper.

**Comment by censink-** [comment]
Update is live on Hub and MGLobby
