### ISSUE TITLE
Forge Installer issue

### ISSUE THREAD

**Issue by LegionOfBoooom** [Lebroncraft/public#65]
Whenever I try to run the forge installer and click to install client, it stops the download at the same place everytime and just freezes it there. The place it freezes at is when it starts the "Downloading Libraries" portion and says 'Unpacking packed files scala-compiler-2.11.1.jar.pack.xz'
I've tried redownloading the client, restarting my computer, etc...  Anything will help at this point!

**Comment by censink-** [comment]
Sorry, but you'll have to ask the guys over at [Forge](http://www.minecraftforge.net/forum/index.php) about this
