### ISSUE TITLE
Forge Crashing?

### ISSUE THREAD

**Issue by BlueBeatz** [Lebroncraft/public#66]
Every time i try to load my world that conatins the mods from the crew modpack, a screen (on the minecraft screen) appears saying that (word-for-word!!!!) :  forge mod loader detected that the backup level.dat is being used. this may happen due to a bug or corruption, continuing can damage your world beyong repair or loase data / progress. its reccomended to create a world backup before continuing. ----- after that it says yes or no and it wont let me click anything, i dont know what to do, and is there a problem that will be continuing to happen and damage my plc? plz help! any information is aprreciated!! :'( NOTE: the only way for me to close minecraft is to go to task manager and manually end it)

**Comment by DamnP** [comment]
hey man, I know the pre-packaged forge for mc 1.7.10 is outdated, there is a newer version. get the 10.13.2.1291 version from here...  http://files.minecraftforge.net/

delete everything, redownload the crew pack mods folder.. get this forge, do what it says except use this forge version  and use the crew craft mods and Flan folders.

**Comment by BlueBeatz** [comment]
Will I have to restart my world?

**Comment by DamnP** [comment]
well, just try updating forge... see if it does it still.
 if not you're good, if it does, probably...

**Comment by censink-** [comment]
You can also back up your world as suggested, by selecting your world and clicking the 'Re-Create' button
