### ISSUE TITLE
Just won't work? 

### ISSUE THREAD

**Issue by FirstH0riz0n** [Lebroncraft/public#67]
I have followed all the instructions as told and still no mods are enabled when i create a new world on the game, It still just plays as normal minecraft?

**Comment by jaypatel10** [comment]
Yea, my minecraft has the same problem. I put in the mod and flan folder, download forge, and in my world it just says 3 mods loaded which all have to do with forge. PLZ HELP

**Comment by studlymuffins69** [comment]
when I download the mods I cant open them to unzip the folder is this the same thing you guys have?

**Comment by studlymuffins69** [comment]
Why was this closed?

**Comment by FirstH0riz0n** [comment]
i have no clue?

**Comment by Castiels-Vessel** [comment]
so is there a solution to this? i have the same trouble.
