### ISSUE TITLE
Please Help! Crashing Problems

### ISSUE THREAD

**Issue by JTaylor47** [Lebroncraft/public#70]
I've downloaded all of the mods and they are working fine but 30 seconds after starting the game, it crashes and keeps saying "shutting down internal server." Im on a mac and I'm not sure how to allocate more ram. Please help.

**Comment by censink-** [comment]
Has been reported before, please pay attention to our guidelines

**Comment by JTaylor47** [comment]
I know im having the same problem and im pretty sure i read it. Doesn't say how he fixed the problem though. Do you know how it was fixed or how to fix this problem?
