### ISSUE TITLE
inventory search function is missing

### ISSUE THREAD

**Issue by Will0wHaven** [Lebroncraft/public#71]
I do not know if you would be able to help me, but I've tried looking this up on all the mods websites and no one has an answer. I logged in this morning and brought up my inventory to look something up and that search function isn't there anymroe...any idea as to what i would need to do to get it back?

Thanks! 

Before: ![2015-03-20_20 55 50](https://cloud.githubusercontent.com/assets/11548790/6772402/e3a5e208-d0ca-11e4-84c0-c8a6ce97487
Now: ![2015-03-22_14 14 35](https://cloud.githubusercontent.com/assets/11548790/6772403/e76f96d6-d0ca-11e4-8ea5-c5d6735b5f52.png)

**Comment by DamnP** [comment]
hot the o key? not zero, but o.
