### ISSUE TITLE
Mods not working (no crashing)

### ISSUE THREAD

**Issue by Zebrahimovic** [Lebroncraft/public#78]
Halp!
So I've only ever used one mod in my life before and it was just click 3 buttons "boom" you are done.
Here I basically followed the instructions and I have Forge 1.7.10 as my profile. When I go into the game though there is no sign of any modding
there is a list of the mods in the options menu on the title screen but in game when I go to mods it just says
Test 1
Test 2
Disabled

Any idea on what the problem is?

Thanks in advance.

**Comment by FirstH0riz0n** [comment]
This happens the exact same as me, Are you using a mac also ?

**Comment by HarleyG85** [comment]
Same issue but i have a few working mods as follows
Kill anything and take that form.
Build weapons and inventory upgrade.
Different map type.
New flowers and blocks.

My only issue is I cant get hats.

**Comment by Zebrahimovic** [comment]
@FirstH0riz0n No, regular acer laptop

**Comment by Zebrahimovic** [comment]
@HarleyG85 Well me personally I could actually do without the hats since I think they look a bit too silly.

**Comment by DevSloth** [comment]
the hat issue is due to a key binding issue. To fix just go to controls and find where "h" is used and then replace it to something else. After that the hats mod will work. Just use h to bring up the hat ui

**Comment by adl3444** [comment]
thanks for the info. problem solved for me
