### ISSUE TITLE
Test 1 test 2 disabled 

### ISSUE THREAD

**Issue by AdamZ1234** [Lebroncraft/public#80]
Do not really understand what i did wrong says i have the the forge mods but i put the flans and mods into my minecraft folder but they do not show up in minecraft do no know what to do to fix this

**Comment by H4CK3dg4mma** [comment]
I get the same thing too

**Comment by AdamZ1234** [comment]
Yeah I figured it out you gotta put the flans and mod folders in the minecraft folder that you find when you open your forge profile and press open dir or something like that and you put the folders in that minecraft folder

**Comment by H4CK3dg4mma** [comment]
Now that i did the launcher won't open it says "Caused by Java.Lang.NullPointerException"

**Comment by AdamZ1234** [comment]
You did the forge installer and everything ?

**Comment by vampireboy1461** [comment]
I got the same problem
