### ISSUE TITLE
It says logging in for over an hour

### ISSUE THREAD

**Issue by brennanjoles** [Lebroncraft/public#83]
the java start says unexpected packet during modded negotiations

**Comment by brennanjoles** [comment]
@censink- helppp

**Comment by MJJMeijerink** [comment]
Make sure to select the forge version in your minecraft launcher:
- Edit profile
- Look for 'use version', select forge
- Save profile and try again

**Comment by brennanjoles** [comment]
i figured that out but now i did everything correct and it starts logging in and says fatally missing blocks and items. @MJJMeijerink

**Comment by MJJMeijerink** [comment]
There's more than one explanation for that issue. One of them is that you have conflicting mods, so make sure you don't have any other mods besides the mods from the modpack.

Another eplanation:
http://forum.feed-the-beast.com/threads/fatally-missing-blocks-and-items.61338/
Has to do with the windows language.

If nothing works, try to do it all over again, you might have done something wrong along the way.
