### ISSUE TITLE
Forge Installer Problem

### ISSUE THREAD

**Issue by Shmackery21** [Lebroncraft/public#87]
I'm a complete noob at modded minecraft. Bare with me. So After I downloaded the zip file for the crew modpack I opened it up, read the install.txt and the second step is to run the forge installer. I opened the forge installer and it gave me three options, to install client, install server, and extract. The path to minecraft is appdata/roaming/.minecraft etc like it should be. I don't want to start a server I just want the client so I tried to install client and it tells me Error: I need to run the version 1.7.10 manually at least once. I have no idea what this means but I am absolutely positive that my minecraft version is 1.8.3. What am I doing wrong???

**Comment by MJJMeijerink** [comment]
Forge can only run on 1.7 and not on 1.8.
What you need to understand is that having minecraft 1.8, doesn't mean you have minecraft 1.7 as well. If you launch minecraft 1.8 from your launcher for the first time, minecraft 1.8 is downloaded. Similarly if you launch minecraft 1.7 from your launcher for the first time, minecraft 1.7 is downloaded.

So they re basically two separate games, and you have to download them separately. Same goes for Minecraft 1.6 and earlier versions.

So to download minecraft 1.7:
- Click on edit profile in your minecraft launcher
- Look for 'Use version:'
- In the drop-down menu, choose: Release 1.7.10
- Click save profile
- Click play, minecraft will now download version 1.7.10 for you.

When minecraft is loaded up you can exit out of minecraft and use the forge installer again.

**Comment by Shmackery21** [comment]
Oh my I think I just fell in love with you. Thank you everything works now. You're the best, peace out bro
