### ISSUE TITLE
Mods dont load

### ISSUE THREAD

**Issue by huahea** [Lebroncraft/public#89]
Hey, wen i tried to play i jsut installed forge, launch the game, put all the mods in the mod folder and then when i launch again i still only have the forge mods, not any other

D4:S down, Halp me

**Comment by papayafinger** [comment]
same with me

**Comment by MJJMeijerink** [comment]
That's weird, it should work. Make sure you are launching minecraft with the right version.

**Comment by papayafinger** [comment]
Yeah I launch with the one that says forge

**Comment by huahea** [comment]
Me too, ive made alot of own modpacks in my times so i know the drill but i just cant get  it to work, are there any modcores like chickencore that needs to be installed separately??

**Comment by huahea** [comment]
Just got it, you need to extrakt all the mods from the folders

**Comment by papayafinger** [comment]
What do you mean by that

**Comment by papayafinger** [comment]
Like have them separately put I did that and still didn't work

**Comment by huahea** [comment]
open the mods and flan folders in the client you downloaded, copy all the files and put them into the mod folder in the .minecraft folder which you can reach by pressing the windows button + r and type %appdata% but you probably know this already :D

**Comment by papayafinger** [comment]
Thanks

**Comment by papayafinger** [comment]
I'll see if it works

**Comment by papayafinger** [comment]
I'll see if that works

**Comment by huahea** [comment]
It should
