### ISSUE TITLE
Block textures arent there

### ISSUE THREAD

**Issue by Opposis** [Lebroncraft/public#93]
each time i find maybe like a seared brick or so, there is no texture to the block.... it is invisible as when the glowstone/fence/x-ray-glitch occured its invisible and i cant tell what the blocks look like. it is very annoying when i cant see the things i need.... pls help if there is a specific pack for it or if there is a way to fix it....

**Comment by MJJMeijerink** [comment]
Are you using optifine with the modpack? I've heard of similar issues with textures from mods and optifine.
