### ISSUE TITLE
Server outdated?

### ISSUE THREAD

**Issue by Kringelum** [Lebroncraft/public#94]
I made my own server with the instructions but when i try to join it it just says that its outdated and its on 1.7.10.

**Comment by MJJMeijerink** [comment]
Make sure you are on playing on minecraft 1.7.10.
- In the launcher, click on edit profile.
- Look for 'use version'
- In the drop-down menu, select minecraft 1.7.10
- Click save profile and start the game.

You can't play minecraft on later versions than the version the server is meant for.
