### ISSUE TITLE
It says to play 1.7.1 once. It wont go pas this

### ISSUE THREAD

**Issue by KENNYP0WERS** [Lebroncraft/public#96]
Hi, so ive downloaded the forge installer. I have tried to run it but it wont go past the icon flashing to play 1.7.1 I already have played this version or do I need to keep it in this version?

Thanks.

**Comment by KENNYP0WERS** [comment]
ok I fixed it lol

**Comment by Castiels-Vessel** [comment]
how did you fix it, im having same trouble

**Comment by soupernoob** [comment]
you play minecraft 1.7.1 once

**Comment by Castiels-Vessel** [comment]
thanks
